### ISSUE TITLE
glitch on ubuntu 16.04 mesa AMD

### ISSUE THREAD

**Issue by Dea1993** [virtual-programming/overlord-linux#12]
i'm playing on ubuntu 16.04 64bit, but after some seconds all mesh became glitched (seems without texture)

my System:
OS: Ubuntu 16.04 64bit
CPU: A10 8700p (carrizo)
GPU: radeon r6
Driver: opensource AMDGPU kernel driver Mesa 11.2
Kernel: 4.7

![20160728192316_1](https://cloud.githubusercontent.com/assets/5217483/17223333/66d5d640-54fc-11e6-8acf-2fc29b268508.jpg)

**Comment by k4os77** [comment]
[https://github.com/virtual-programming/overlord-linux/issues/2](url)

**Comment by vpltd-peterm** [comment]
This is fixed in the Mesa 12.1.0 driver, as it is a driver problem I'm closing this.
