### ISSUE TITLE
Consistent crash at one point in Heaven's Peak

### ISSUE THREAD

**Issue by cberkenpas** [virtual-programming/overlord-linux#13]
I've tried 5 times now, and each time the game has crashed in exactly the same spot.

The game always crashes at the part of Heaven's Peak castle where you find a blocked exit, and the game switches to a cut scene where you see some peasants asking to let you in saying "Let us in! We are your lost sheep!"

It crashes where a minion starts to say something along the lines of "Sheepies? Where are sheepies?". The sentence is never finished (you can see the sentence in the subtitles though) and the game crashes.

Here are screenshots of the exit and the cut scene assuming I've uploaded them correctly:
![20160728220803_1](https://cloud.githubusercontent.com/assets/2414368/17238409/47214136-5510-11e6-94e8-1aec360447b6.jpg)
![20160728220821_1](https://cloud.githubusercontent.com/assets/2414368/17238413/50371ffc-5510-11e6-8a0a-ca99891ed3fc.jpg)
![20160728220829_1](https://cloud.githubusercontent.com/assets/2414368/17238416/56acc4d6-5510-11e6-9a45-38c07a635b80.jpg)
![20160728220833_1](https://cloud.githubusercontent.com/assets/2414368/17238422/5f4b0e36-5510-11e6-86ac-7c29e04832b5.jpg)

On a related note, the crash report tool that pops up doesn't work for me either. Whenever I tried to send a report, it ends up just hanging.

Otherwise the game seems to be rock solid. Prior to this, I played for several hours straight without a single issue.

**Comment by cberkenpas** [comment]
Looks like the crash report dialog is able to provide details, even if it isn't able to send them. Below is the relevant portion with redundant entries removed for brevity.

Looks like there's some missing files. When I verify game data, it reports that there's 72 missing files and that it will download them. It seems to download them suchitcessfully, except the download occurs way too quickly. And if I try to verify again, the same thing will happen:
![72-files](https://cloud.githubusercontent.com/assets/2414368/17239696/fb721476-551a-11e6-9c57-835b8a550ef5.png)

[thread 00000009][I][10715]: Uniform buffer mAsmPixelFloatStreamedBuffer (0xefda7a24) now has 2 internal buffers, taking 8192000 bytes
[thread 00000009][I][12426]: Uniform buffer mAsmVertexFloatStreamedBuffer (0xefda79e0) now has 2 internal buffers, taking 8192000 bytes
[thread 00000009][I][12573]: Uniform buffer mCommonVariablesStreamedBuffer (0xefda7bbc) now has 2 internal buffers, taking 294912 bytes
[thread 00000005][I][18033]: libAudioFile error: (5) file missing data -- read 228592 frames, should be 229041
[thread 00000005][I][18049]: libAudioFile error: (5) file missing data -- read 228592 frames, should be 229041
[thread 00000005][I][20825]: libAudioFile error: (5) file missing data -- read 36738 frames, should be 37269
[thread 00000009][I][27983]: Uniform buffer mAsmVertexFloatStreamedBuffer (0xefda79e0) now has 3 internal buffers, taking 12288000 bytes
[thread 00000005][I][27990]: libAudioFile error: (5) file missing data -- read 105768 frames, should be 106718
[thread 00000005][I][28000]: libAudioFile error: (5) file missing data -- read 269412 frames, should be 270281
[thread 00000005][I][28002]: libAudioFile error: (5) file missing data -- read 51867 frames, should be 52384
[thread 00000005][I][28008]: libAudioFile error: (5) file missing data -- read 200018 frames, should be 200390
[thread 00000005][I][28011]: libAudioFile error: (5) file missing data -- read 105768 frames, should be 106718
[thread 00000005][I][28014]: libAudioFile error: (5) file missing data -- read 51867 frames, should be 52384
[thread 00000005][I][28023]: libAudioFile error: (5) file missing data -- read 146952 frames, should be 147457
[thread 00000009][I][28030]: Uniform buffer mAsmVertexFloatStreamedBuffer (0xefda79e0) now has 4 internal buffers, taking 16384000 bytes
...
[thread 00000005][I][117029]: libAudioFile error: (5) file missing data -- read 42861 frames, should be 44025
[thread 00000005][I][119287]: libAudioFile error: (5) file missing data -- read 389831 frames, should be 391210
[thread 00000005][I][130664]: libAudioFile error: (0) unrecognized audio file format
[thread 00000005][I][130664]: libAudioFile error: (1) null file handle
[thread 00000005][I][130664]: libAudioFile error: (1) null file handle
[thread 00000005][I][130664]: libAudioFile error: (1) null file handle
[thread 00000005][I][130665]: libAudioFile error: (1) null file handle
[thread 00000005][I][130665]: libAudioFile error: (1) null file handle
[thread 00000005][I][130665]: libAudioFile error: (1) null file handle
[thread 00000005][I][130726]: ===enforcing log flush===

**Comment by cberkenpas** [comment]
I went and tested this on my laptop. Same issue. I then deleted Overlord and Raising Hell and reinstalled them, same issue. Hope that helps.

**Comment by vpltd-peterm** [comment]
The "72 files failed to validate" is not related - the Windows install also does this (except its 76 files there) and works. I'll keep looking.

**Comment by Kwaadpepper** [comment]
I can confirm this, also having this issue, except the report tool works for me. 
But all files were validated by steam.

**Comment by Gunman1982** [comment]
As a workaround: You can skip cutscenes by hitting space.

Don't know if related but in the area of Heavens Peak I get a lot of crashes anyhow. Most of the time it seems when a minion comments on something.

**Comment by vpltd-peterm** [comment]
It is a sound engine problem... the game tries to play a bad WAV file at this point. The original Miles Sound System code ignores it, but our code hits an assert. I will have a patch for it soon

**Comment by vpltd-peterm** [comment]
You should see an update to Overlord, to BuildID 1254803 which should fix this problem.

**Comment by vpltd-peterm** [comment]
Can we confirm this is fixed ?

**Comment by cberkenpas** [comment]
Yes, it is absolutely fixed. Sorry, I assumed this was already known!
