### ISSUE TITLE
Crash at Minion Sacrifice Animation When Forging

### ISSUE THREAD

**Issue by Timesquare** [virtual-programming/overlord-linux#15]
When sacrificing any number of minions greater than zero of any type for either upgrading or forging at the Forge, the game crashes. Specifically, the animation sequence plays successfully just before the minions are supposed to appear, at which point the game crashes.

To reproduce the bug:

1.  Go to the Forge
2.  Select any upgrade or forgable equipment
3.  Set at least one minion of any type to be sacrificed
4.  Order the forging
5.  Experience crash

```
Desktop Environment:
    Window Manager: i3
    Compositor: None

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected
    
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3f
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  3600 Mhz
    12 logical processors
    6 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.6.4-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11803000
    X Window Manager:  i3
    Steam Runtime Version:  steam-runtime-beta-release_2016-06-15
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 670/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 367.35
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1189
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3200 x 1080
    Primary Display Size: 20.04" x 11.26"  (22.95" diag)
                                            50.9cm x 28.6cm  (58.3cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Realtek ALC892
    
Memory:
    RAM:  15947 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  953868 Mb
    Largest Free Hard Disk Block:  79390 Mb
    VR Headset: None detected
    
    Sat Jul 30 16:20:32 2016 GMT: file ''/tmp/dumps/crash_20160730122024_22.dmp'', upload yes: ''CrashID=bp-67dc5313-bbd9-49e1-bb9f-77dfa2160730''
    Sat Jul 30 23:16:55 2016 GMT: file ''/tmp/dumps/crash_20160730191647_19.dmp'', upload yes: ''CrashID=bp-3f95c36c-db3b-41cf-a7d2-6366b2160730''
```
    
[eon.txt](https://github.com/virtual-programming/overlord-linux/files/392154/eon.txt)
And the crash reporter code: 5AYAK2NKJL

**Comment by vpltd-peterm** [comment]
Unfortunately the crash dump was corrupted in some way. We have had a few reports of problems with the nvidia 367.35 driver we're keeping an eye on. Could you possibly test with 364.19 ?

**Comment by Timesquare** [comment]
I've downgraded to 364.19, and still get the crashes.

[eon.txt](https://github.com/virtual-programming/overlord-linux/files/392266/eon.txt)

Crash reporter code is: P8DCXFNAU2

And a md5sum of the crash dump:
07a4079415e27a7952b65282d551d6a9  1509fd39-eea9-93a4-319162c3-3903ad6c.dmp

**Comment by vpltd-peterm** [comment]
Cannot reproduce this on the same drivers under Manjaro. 
Have you verified the game files in Steam?

**Comment by Timesquare** [comment]
After verifying files for both Overlord and Overlord: Raising Hell, the game still crashes when forging. I'll see about installing Ubuntu, and see if I can reproduce the crash there.

**Comment by Timesquare** [comment]
Reinstalling steam fixed the crash.

**Comment by vpltd-peterm** [comment]
Reinstalling the game in Steam, or Steam itself ? The latter would be very odd :)
