### ISSUE TITLE
GateGuards_01.mp3 not found

### ISSUE THREAD

**Issue by Pernet** [virtual-programming/overlord-linux#18]
found in ~/.local/share/vpltd/Overlord/eon.txt

`[thread 00000005][I][755567]: MSS: Failed to open file in AIL_open_stream! File path:'C:\usr\games\steam-library\steamapps\common\Overlord\Resources\Songs\GateGuards_01.mp3,0,true'`

**Comment by vpltd-peterm** [comment]
Not a bug in the port, this happens on the Windows version of the game too, but the error message is invisible there.
