### ISSUE TITLE
Rendering issues with Mesa

### ISSUE THREAD

**Issue by vpltd-peterm** [virtual-programming/overlord-linux#2]
Currently the game will not render 100% correctly with Mesa - you may see white or miscoloured patches. This has been traced down to a Mesa bug by a Mesa developer (thanks Nicolai Hähnle!) and will be patched by them.

Apart from this, we have found the game works very well under Mesa with AMD cards, and actually gives better performance than fglrx does ! We look forward to seeing Mesa patched and able to officially run the game :)

**Comment by k4os77** [comment]
Any ETA for the patch?

**Comment by vpltd-peterm** [comment]
Not that I'm aware of.

**Comment by vpltd-peterm** [comment]
I'd just like to be clear on this - we have reached out to Mesa developers with this game (and our previous titles too). The problem with this game not rendering correctly on RadeonSI is due to issues in Mesa itself (particularly, how Varyings are handled between vertex and fragment shaders).

I believe patches have already been worked on and submitted, and so the problems will be fixed with time, and we are providing all the support we can (including free copies of the game). Ultimately though, it is down to Mesa to correct the problems. This is why we only "officially" support the proprietary drivers, currently.

**Comment by Arienreth** [comment]
Just installed the game from steam, i own a HD5770 and use mesa, the game runs fast, although with ALOT of graphical errors that seem by the description to be related to this bug.
I write here cause the developer mentions a bug present in radeonSI but i use r600g and the bug seems if not the same, at least related.
Thanks for all the work.

**Comment by vpltd-peterm** [comment]
I'm personally very keen to see r600 and radeonsi support this game well :)

**Comment by vpltd-peterm** [comment]
@Arienreth, can you take some screenshots to show what you mean?

**Comment by Arienreth** [comment]
![overlord screen](https://cloud.githubusercontent.com/assets/20690590/17193888/06bf182a-544d-11e6-81d8-406c42913379.png)

Let me know if theres anything else usefull i can send!

**Comment by vpltd-peterm** [comment]
Yeah, it looks similar to the rendering issues we've already seen. The cause is likely to be the same. We also know that llvmpipe (the Mesa software renderer) has issues so it is something at the core of Mesa rather than a specific hardware driver.

**Comment by k4os77** [comment]
@vpltd-peterm Why don't you test games on Mesa and get in touch with them before the release? (friendly-question)

**Comment by Arienreth** [comment]
![overlord ii screen](https://cloud.githubusercontent.com/assets/20690590/17194057/037eee82-544e-11e6-9c65-7ecb194a9458.png)

Overlord II does not share the same issue. Just a fiy. :)

Though that one crashes violently when i try to run it fullscreen. Ill poke that side of github to see if i relevant info is required.

"Glad" to know it's not only on r600, gives it a better chance it will be solved, thanks for the replies :)

**Comment by vpltd-peterm** [comment]
@k4os77 we did, and made prerelease copies of the game available to some of the Mesa developers.

**Comment by lordheavy** [comment]
Probably this mesa patch:
https://patchwork.freedesktop.org/patch/100750/

**Comment by s3rg3** [comment]
Fixed on r600 with latest mesa-git.

By the way thank you lordheavy for your Mesa-git repo.

**Comment by Dea1993** [comment]
i've a similar problem on overlord 1 and overlord 2

**Overlord 1**
the problem not start immediatly but after few seconds

![20160728192316_1](https://cloud.githubusercontent.com/assets/5217483/17223981/45fd9cde-54ff-11e6-843a-14232eb4a204.jpg)

**Overlord 2**
this is a more critical issue... infact i can't see anything.
furthermore, also killing the game... the glitch remain.
this is alway the mesa problem you mentioned?

![20160728193222_1](https://cloud.githubusercontent.com/assets/5217483/17224003/5a7738b4-54ff-11e6-888e-b5807fcfe6a1.jpg)

**Comment by vpltd-peterm** [comment]
I have filed this bug:
https://bugs.freedesktop.org/show_bug.cgi?id=97022

Note that while the topic of the bug says "windowed mode", that was just the easiest way to cause the problem to happen. It also happens fullscreen.

**Comment by vpltd-peterm** [comment]
For people experiencing issues with the Mesa driver, please file it as a bug report on Mesa. This should help raise it's priority with them. We have already offered free copies of the game to Mesa developers so that they can work on it.

**Comment by boltronics** [comment]
I just hit this, and can confirm that upgrading to the latest Mesa from git with my Radeon R9 Fury X allows the game to run fine without corruption. Thanks for helping upstream Mesa!

**Comment by xpris** [comment]
My issues on Mesa is now fixed (I get new mesa update on PPA Oibaf) and after that this issue gone.
My issue looking like this: http://steamcommunity.com/app/11450/discussions/0/353915309331092429/

**Comment by vpltd-peterm** [comment]
Hmm, I did not notice any slow down as a result of the Varyings fix. Try removing the eONprecompiledShaders32.dat file and allow it to regenerate

**Comment by Dea1993** [comment]
someone has tried padoka ppa for mesa git??

**Comment by vpltd-peterm** [comment]
I have used the Padoka PPA myself. To date, it is slightly behind Oibaf PPA in terms of mesa version, so if you want the latest, stick with Oibaf.

**Comment by Dea1993** [comment]
oibaf ppa broke my xorg.
when i reboot, ubuntu starts on failsafe mode, and i must enter in recovery to ppa-purge the oibaf ppa

**Comment by vpltd-peterm** [comment]
With the latest build of Mesa 12.1.0, available in Oibaf today, the display corruption/system lockup problems should be solved. Please try it :)

**Comment by vpltd-peterm** [comment]
I can confirm here the issue is fixed using Mesa 12.1.0, as of commit bc5df3b321c5393b2f10115cfa5acc8f11bd7146
