### ISSUE TITLE
Shadows/textures problem.

### ISSUE THREAD

**Issue by Yalvor** [virtual-programming/overlord-linux#20]
Here is a few screen shots.
![20160919040520_1](https://cloud.githubusercontent.com/assets/22283677/18620623/516490e0-7e27-11e6-86c4-1956a2b583d0.jpg)
![20160919040542_1](https://cloud.githubusercontent.com/assets/22283677/18620625/5863084a-7e27-11e6-9254-0532f7b3a83a.jpg)
![20160919040548_1](https://cloud.githubusercontent.com/assets/22283677/18620626/59788160-7e27-11e6-831e-78c91cefb6f6.jpg)
![20160919040553_1](https://cloud.githubusercontent.com/assets/22283677/18620627/5ab2d8be-7e27-11e6-9c2a-a68e24cc82a0.jpg)
![20160919040557_1](https://cloud.githubusercontent.com/assets/22283677/18620628/5c47af06-7e27-11e6-8a02-41a6f3006f50.jpg)
Played Overlord 1+ 2 on Windows on the same computer before, worked like a charm.
Checked file integrity, constant 144 files missing recovery, not sure if thats the problem.
Video card ATI Radeon HD 4770 512 Mb
Tried different settings (low/high/custom shadows on/off). Nothing changed in this matter.
What other information needed for this problem?

**Comment by vpltd-peterm** [comment]
You are using old Mesa drivers, which have bugs causing the incorrect rendering. You either need to use the Mesa 12.1.0-development drivers, or install AMD's Catalyst (fglrx) driver. However the Radeon HD4770 is an old card, and likely no longer supported by Catalyst.

If you are using Ubuntu, we recommend the Oibaf PPA - https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers

**Comment by vpltd-peterm** [comment]
Duplicate of #2

**Comment by Yalvor** [comment]
Fixed, thank you.
