### ISSUE TITLE
There is no linux version on GOG.com

### ISSUE THREAD

**Issue by Vednier** [virtual-programming/overlord-linux#24]
As legitimate owner of Overloard + RAISING HELL copy on GOG.com https://www.gog.com/game/overlord_raising_hell i'd like to ask why GOG.com customers dont have access to its Linux version?
Game here is sold legally and money paid was real, but there is such port on Steam and, still, not on GOG.com.
As much as i know Virtual Programming had store on which they sold it, at least, DRM-free but now its gone (i see just mention of Steam on https://www.deliver2.com/products/) and its look like Steam is only place to get it now which is absolutely not fair.
How can we get it on GOG?

**Comment by vpltd-peterm** [comment]
I will enquire into this but the likely reason is due to licensing agreement between us and Codemasters. We were contracted by them to do the port, so the end result is their property and it is up to them where they sell it.

**Comment by Vednier** [comment]
But they released said port on Steam, right? Same Codemasters also distribute Overlord on GOG, so if its their property why should they decline customers on another distribution platform? Anyway, please ask them.

**Comment by vpltd-peterm** [comment]
My guess would be revenue split. Steam gives feedback on which platform the game is being played. GOG does not. Effectively, if we were to sell on GOG as is, we would not receive any payment.

**Comment by vpltd-peterm** [comment]
I have been told we cannot discuss sales issues here. Please use our support site for this:
http://www.vpltd.com/support/
