### ISSUE TITLE
Continuous vibration when playing with joypad

### ISSUE THREAD

**Issue by strycore** [virtual-programming/overlord-linux#4]
I've changed the input device to Gamepad on the configuration tool and when starting the game, the gamepad won't stop vibrating.
I've tried turning off vibrations in the game settings but this has no effect.

The joypad used is a standard wired Xbox 360 controller.

[eon.txt](https://github.com/virtual-programming/overlord-linux/files/385060/eon.txt)

**Comment by vpltd-peterm** [comment]
This is a bug in the Xpad kernel driver. Please see https://github.com/paroj/xpad/issues/27

However, not all distro's have updated their version of the driver. We suggest either doing so manually, or switching to xboxdrv instead.

**Comment by vpltd-peterm** [comment]
I have added the command line option --eon_disable_forcefeedback which will prevent the game querying for force feedback support.
