### ISSUE TITLE
Config tool requires gtk3

### ISSUE THREAD

**Issue by WorMzy** [virtual-programming/overlord-linux#5]
Hey, I was wondering whether there is a way to generate a Settings.dat file without the use of the bundled configuration tool (overlord-config), as this tool requires gtk3 (which I won't install on my system for various reasons). Even if you just do a code dump of the existing configuration tool and let the community create an unsupported configuration tool that relies on qt or gtk2 instead, that'd be great.

If not, no worries.

Cheers!

**Comment by vpltd-peterm** [comment]
I have created default settings files for the games here:

http://developer.vpltd.com/public/overlord/overlord1_default_settings.zip
http://developer.vpltd.com/public/overlord/overlord2_default_settings.zip

These will set the game up with default controls, High detail settings (vsync on) and 1024x768 resolution.

I will have to check whether I am allowed to release the code that deals with reading/writing the settings file format...

**Comment by vpltd-peterm** [comment]
Here is the source code for the C++ class I wrote, which deals with writing the Settings.dat format used by Overlord 1 and 2. This should allow you to write your own tool to configure the game.

Please note that the code remains Copyright Virtual Programming Ltd, and no official support can be given for it. Have fun :)

**Comment by WorMzy** [comment]
That's awesome! Thanks for going above and beyond and actually indulging my selfish request. And for providing defaults so I can actually play in the mean time. You're awesome!
