### ISSUE TITLE
Bluetooth module detected as a gamepad

### ISSUE THREAD

**Issue by hidekin** [virtual-programming/overlord-linux#6]
Hi , 

I have this problem on Overlord and Overlord II , when my bluetooth module that is on the motherboard is enabled the game detects the module as a gamepad then the camera move by itself if the dpi of my mouse is too high.

CPU :Intel  I7 3820 3.6Ghz
GPU : Nvidia Gtx 1070 8GB (Drivers 367.35)
RAM : 16GB DDR 2133Mhz
OS: Archlinux
Bluetooth : Atheros Communications, Inc. AR3011 Bluetooth

[eon.txt](https://github.com/virtual-programming/overlord-linux/files/385893/eon.txt)

Thank you very much

**Comment by vpltd-peterm** [comment]
Hmm, actually it looks as if Steam is reporting the Bluetooth module as a Steam controller:

03000000de280000ff11000001000000,Valve Streaming Gamepad,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3
03000000de280000fc11000001000000,Steam Controller,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,

This is being passed by the SDL_GAMECONTROLLERCONFIG environment variable, which Steam is setting.

As a workaround, edit "overlord" and add the following line, just after the hashbang:
unset SDL_GAMECONTROLLERCONFIG

**Comment by hidekin** [comment]
The workaroud worked  :+1: 

Thanks a lot
